Add mercurial script
dracula/tmux pull request #226
Opened 2023-07-04 12:48 UTC by pele1410

I added support for tracking mercurial repositories similar to the existing git repository support.

```
set -g @dracula-plugins "hg time"
```

Clean repository
![clean](https://github.com/dracula/tmux/assets/876723/2ecefa29-ea1d-48ba-be1e-f0d01e5c6833)

Dirty repository
![dirty](https://github.com/dracula/tmux/assets/876723/bee0f899-72da-4317-b58c-29dd7f2f6a0c)

Tested each configuration:
```
set -g @dracula-hg-disable-status true
set -g @dracula-hg-show-diff-symbol "^"
```
![hg-disable-status](https://github.com/dracula/tmux/assets/876723/5b5aaace-4b1c-4591-8f64-a7ee578374c9)

```
set -g @dracula-hg-no-untracked-files true
```
![no-untracked-files](https://github.com/dracula/tmux/assets/876723/6b83e9b1-bf2b-4a1a-9ec4-f7aefa01aadf)

```
set -g @dracula-hg-no-repo-message "no-hg"
```
![hg-no-repo-message](https://github.com/dracula/tmux/assets/876723/938e395e-ec6d-45ac-8908-30c27c128486)

```
set -g @dracula-hg-show-current-symbol "@"
```
![hg-show-current-symbol](https://github.com/dracula/tmux/assets/876723/28c168d7-1582-4486-b520-42d707bcf58a)

2023-07-08 23:41 UTC, ethancedwards8 requested changes

2023-07-08 23:41 UTC, ethancedwards8 commented on scripts/hg.sh
> +IFS=' ' read -r -a no_untracked_files <<< $(get_tmux_option "@dracula-hg-no-untracked-files" "false")
Can you document these in INSTALL.md?

2023-07-09 00:05 UTC, pele1410 commented on scripts/hg.sh
> +IFS=' ' read -r -a no_untracked_files <<< $(get_tmux_option "@dracula-hg-no-untracked-files" "false")
No problem, thought I had them all

2023-07-09 00:05 UTC, pele1410 commented on scripts/hg.sh
> +IFS=' ' read -r -a no_untracked_files <<< $(get_tmux_option "@dracula-hg-no-untracked-files" "false")
Updated

2023-07-09 20:24 UTC, ethancedwards8 approved these changes

2023-07-09 20:24 UTC, merged

2023-07-09 20:24 UTC, ethancedwards8 commented
Thank you for your contribution!